apiVersion: "k0sctl.k0sproject.io/v1beta1"
kind: "cluster"
spec:
  hosts:
  - installFlags:
    - "--enable-cloud-provider"
    - "--kubelet-extra-args=\"--cloud-provider=external\""
    role: "controller+worker"
    ssh:
      address: "18.157.184.108"
      keyPath: "./aws_private.pem"
      user: "ubuntu"
  - installFlags:
    - "--enable-cloud-provider"
    - "--kubelet-extra-args=\"--cloud-provider=external\""
    role: "worker"
    ssh:
      address: "3.68.116.251"
      keyPath: "./aws_private.pem"
      user: "ubuntu"
  - installFlags:
    - "--enable-cloud-provider"
    - "--kubelet-extra-args=\"--cloud-provider=external\""
    role: "worker"
    ssh:
      address: "35.158.135.77"
      keyPath: "./aws_private.pem"
      user: "ubuntu"
  - installFlags:
    - "--enable-cloud-provider"
    - "--kubelet-extra-args=\"--cloud-provider=external\""
    role: "worker"
    ssh:
      address: "3.74.229.178"
      keyPath: "./aws_private.pem"
      user: "ubuntu"
  k0s:
    config:
      apiVersion: "k0s.k0sproject.io/v1beta1"
      kind: "Cluster"
      metadata:
        name: "k0s-cilium-cluster"
      spec:
        api:
          address: "18.157.184.108"
          externalAddress: "18.157.184.108"
          k0sApiPort: 9443
          port: 6443
          sans:
          - "18.157.184.108"
          tunneledNetworkingMode: false
        controllerManager: {}
        extensions:
          helm:
            charts:
            - chartname: "cilium/cilium"
              name: "cilium"
              namespace: "kube-system"
              version: "1.13.1"
            - chartname: "aws-cloud-controller-manager/aws-cloud-controller-manager"
              name: "aws-cloud-controller-manager"
              namespace: "kube-system"
              values: |
                args:
                  - --v=2
                  - --cloud-provider=aws
                  - --allocate-node-cidrs=false
                  - --cluster-cidr=172.20.0.0/16
                  - --cluster-name=k0s-cilium-cluster
                nodeSelector:
                  node-role.kubernetes.io/control-plane: "true"
              version: "0.0.7"
            repositories:
            - name: "cilium"
              url: "https://helm.cilium.io/"
            - name: "aws-cloud-controller-manager"
              url: "https://kubernetes.github.io/cloud-provider-aws"
            - name: "aws-ebs-csi-driver"
              url: "https://kubernetes-sigs.github.io/aws-ebs-csi-driver"
        installConfig:
          users:
            etcdUser: "etcd"
            kineUser: "kube-apiserver"
            konnectivityUser: "konnectivity-server"
            kubeAPIserverUser: "kube-apiserver"
            kubeSchedulerUser: "kube-scheduler"
        network:
          kubeProxy:
            disabled: false
            mode: "iptables"
          podCIDR: "10.244.0.0/16"
          provider: "custom"
          serviceCIDR: "10.96.0.0/12"
        storage:
          type: "etcd"
        telemetry:
          enabled: true
    dynamicConfig: false
    version: "1.26.2+k0s.0"